### ISSUE TITLE
Errata Chapter 1.3, page 9, second paragraph

### ISSUE THREAD

**Issue by amacias** [adonovan/gopl.io#1]
Hi!

Not sure how to report errata in the preview chaptar available at http://gopl.io/, didn't find anything in the preface about how to proceed. I have no idea if this PDF is considered final or not, and perhaps all typos and errata are already fixed for the final version, but just in case I thought I would open a thread here so that anyone can report errata and hopefully fix as many of those as possible before the book goes to print.

Feel free to close this if it's not appropriate :)

Thanks!

**Comment by amacias** [comment]
On page 9, chapter 1.3, second paragraph reads:

>The key may be of any type whose values can compared with ==

The phrasing seems odd/wrong, seems that it's missing a `be`:

>The key may be of any type whose values can be compared with ==

**Comment by alandonovan** [comment]
That is indeed a mistake.  Thanks for reporting it.

**Comment by amacias** [comment]
Anytime, thank you for the awesome work! Would you prefer to keep this thread for others to report errata or is it preferable to open a separate issue for each one?

**Comment by alandonovan** [comment]
Giving each separate issue a separate "issue" makes the most sense, I think.

**Comment by amacias** [comment]
Perfect, changing the name of this one and closing :)
