### ISSUE TITLE
P290, ch10.7

### ISSUE THREAD

**Issue by chai2010** [adonovan/gopl.io#14]
> You can run **go help** to see the index of its built-in documentation,
but for reference, we’ve listed the most commonly used commands below:
>

But the below command is `go`, not `go help`.

```
$ go
...
	build            compile packages and dependencies
	clean            remove object files
...
```

**Comment by alandonovan** [comment]
You are correct; we were trying to show that `go` is a shorthand for `go help` with no arguments.
