### ISSUE TITLE
p52 Operator precedence

### ISSUE THREAD

**Issue by bassu** [adonovan/gopl.io#15]
On p52, below the list of operators it reads, `Operators at the same level associate to the left`. 
It should have said: "to the right".

Because it is in clash to what the Go Spec says,
```
Binary operators of the same precedence associate from left to right. 
For instance, x / y * z is the same as (x / y) * z. 
```

**Comment by adonovan** [comment]
An operator ⊕ is described as "left associative" if the leftmost operation in a sequence x ⊕ y ⊕ z is evaluated first.  That is, the sequence is equivalent to (x ⊕ y) ⊕ z.  Go's binary operators are left-associative.

The phrase in the spec ("associates from left to right") and the phrase in the book ("associates to the left") mean the same thing, namely left-associative, despite the paradoxical difference in their use of the particle "to".  The form in the book is more widely used in programming literature.

**Comment by bassu** [comment]
@adonovan Cool. Thanks for the instant gratification :-)
