### ISSUE TITLE
Errata 10.5 Blank Imports

### ISSUE THREAD

**Issue by jecolon** [adonovan/gopl.io#16]
First of all, congratulations on the best book ever covering the Go language. :)

In section 10.5, Blank Imports, near the end, the code has an import to database/mysql which I think should be database/sql .  I'm reading online via Safari, so I don't know the print page number.

Best,
José

**Comment by adonovan** [comment]
You're absolutely right; I've posted an erratum.  Thanks for pointing out the mistake.
