### ISSUE TITLE
Content question from Ch. 4

### ISSUE THREAD

**Issue by dave-r12** [adonovan/gopl.io#21]
Hello, I've been going through the book (which is great BTW), and wanted to ask a question around some of the content. In chapter 4, when discussing why deep equivalence is problematic for slices, the text reads:

> First, unlike array elements, the elements of a slice are indirect, making it possible for a slice to contain itself. Although there are ways to deal with such cases, none is simple, efficient, and most importantly, obvious.

I am struggling to wrap my head around what it means for a slice to contain itself. Can you help me understand? Apologies if this is the wrong venue for this.

**Comment by alandonovan** [comment]
See: http://play.golang.org/p/5ZCe-ZbGG7

Sorry if mentioning this in passing was cryptic, but we didn't want to elaborate on something so esoteric.

Exercise: construct a map that contains itself as a value.

Exercise: using the declaration `type state map[rune]state`, construct a state machine that recognizes the regular language "b(an)*a".

**Comment by dave-r12** [comment]
Wow, that is mind-boggling! Thanks for the response.
