### ISSUE TITLE
Preface: The Origins of Go

### ISSUE THREAD

**Issue by chai2010** [adonovan/gopl.io#8]
I think the figure should include Limbo language.

In Rob Pike's talk (2012): Go Concurrency Patterns, he said (at page 10):
Go is the latest on the Newsqueak-Alef-Limbo branch, distinguished by first-class channels.

http://talks.golang.org/2012/concurrency.slide#10
http://doc.cat-v.org/plan_9/2nd_edition/papers/alef/

**Comment by alandonovan** [comment]
We included Limbo in an early draft but after discussion with reviewers we decided to remove it.
