### ISSUE TITLE
Chapter 8.10, p254 wording

### ISSUE THREAD

**Issue by micahhausler** [adonovan/gopl.io#9]
The last sentence in the paragraph defining the broadcaster on page 254 reads:

> The only information recorded about each client is the identity of its outgoing message chan-
> nel, about which more later.

The "about which more later." could probably be re-worded to something more clear. (This may be academic speech which I never learned.)

**Comment by alandonovan** [comment]
I'm not sure it's especially academic, but it's a common idiom in book writing:
https://www.google.com/search?tbm=bks&hl=en&q=about+which+more+later
